### ISSUE TITLE
UCS/UPS tracking issue

### ISSUE THREAD

**Issue by LPTK** [hkust-taco/mlscript#151]
Issue to track the parts of the UCS implementation that are still incomplete or wrong – please update with more cases as you find them.

### Translation

 - [x] Support virtual constructors for pattern matching against tuples. **Note as of Jan 2024**: We implemented simple tuple pattern in #194 and we will support advanced tuple patterns, for example, splice tuple patterns, in the near future.
 - [x] Do not duplicate default cases and insert local function definitions instead.
   - **Note as of Jan 2024**: We paved the road for this in #194 and we will implement this feature in the near future.
   - **Note as of Nov 2025**: This has been solved in #336. Instead of using local functions, we use `Block` and `Break`.

### Locations

 - ~~Track scrutinee locations with `Scrutinee.Source`~~. (Note: it was removed in new desugarer.)
 - [x] No location reported in:

    ```scala
    fun testF(x) = if x is
      Foo(a) then a
      Foo(a) then a
    //│ ╔══[WARNING] duplicated branch
    //│ ╙──
    ```

### Reporting

 - [ ] Warn when an `is` test has a single pattern
    Though maybe we shouldn't warn when it's conjuncted with other things, as then the `is` may be used to bind expressions, as in `if xs is x :: xs and mapPartition(f, xs) is (as, bs) and ...`

### String patterns overhaul

- [ ] Make a PR that overhauls string patterns; currently, they misbehave in some cases; eg
    <details>
    <summary>Example</summary>
    
    ```fs
    pattern Digits = ("0"..="9") ~ (Digits | "")
    pattern DigitsCommas = Digits | Digits ~ "," ~ DigitsCommas
    pattern Integer = "0" | ("1"..="9") ~ (DigitsCommas | "")
    pattern FractionalPart = "." ~ Digits
    pattern ExponentPart = ("e" | "E") ~ ("+" | "-" | "") ~ Integer
    
    // FIXME: does not work!
    // pattern NumberStr = Integer ~ (FractionalPart | "") ~ (ExponentPart | "")
    
    // Works
    pattern NumberStr = Integer | Integer ~ FractionalPart ~ (ExponentPart | "")
    
    // FIXME: `Number` doesn't recognize commas
    pattern AsNumber = (NumberStr & n) => Number(n)
    ```
    
    </details>

### Fix pattern extraction semantics

- [ ] Patterns like `Pair(0 => 1, 0 => 1)` should rebuild the outer ctors
- [ ] Patterns like `C(_, 0 => 1)` should fail when the first param of `C` is private, as the thing can't be rebuilt
- [ ] Patterns like `P(Transf)` should warn about a discarded transformation when `P` is a HOP – users should write `P(Transf as _)` instead

### Fixed point patterns

- [ ] Avoid retraversing rec pattern prefixes when no change happened (see: EvaluationContexts2, StackParse)

**Comment by LPTK** [comment]
- [x] hygiene

    ```ts
    :NewParser
    :NewDefs
    :NoJS
    
    class Union<Region>(a: Region, b: Region)
    //│ class Union[Region](a: Region, b: Region)
    
    // * [FIXME:UCS] unhygienically desugars to:
    // | | | | Desugared term: case x of { Union => let x = (x).a in let y = (x).b in x }
    fun hmm(x) =
      if x is Union(x, y) then x
    //│ fun hmm: Union[{b: anything} & 'a] -> 'a
    
    fun hmm(x) =
      if x is Union(z, y) then x
    //│ fun hmm: Union['Region] -> Union['Region]
    ```

**Comment by LPTK** [comment]
- [x] There's a problem witth he builtin true/false in the current UCS impl

```ts
:NewParser
:NewDefs

module Nil
class Cons[A](head: A, tail: Cons[A] | Nil)
//│ module Nil()
//│ class Cons[A](head: A, tail: Cons[A] | Nil)

// FIXME
fun filtermap(f, xs) = if xs is
  Nil then Nil
  Cons(y, ys) and f(ys) is
    false then filtermap(f, ys)
    true then Cons(y, filtermap(f, ys))
    [true, z] then Cons(y, filtermap(f, ys))
//│ ╔══[ERROR] identifier not found: ys
//│ ║  l.26: 	  Cons(y, ys) and f(ys) is
//│ ╙──      	                    ^^
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.26: 	  Cons(y, ys) and f(ys) is
//│ ║        	                  ^^^^^^^^
//│ ║  l.27: 	    false then filtermap(f, ys)
//│ ║        	^^^^^^^^^
//│ ╟── reference of type `false` is not an instance of type `number`
//│ ║  l.27: 	    false then filtermap(f, ys)
//│ ╙──      	    ^^^^^
//│ ╔══[ERROR] Type mismatch in application:
//│ ║  l.26: 	  Cons(y, ys) and f(ys) is
//│ ║        	                  ^^^^^^^^
//│ ║  l.27: 	    false then filtermap(f, ys)
//│ ║        	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//│ ║  l.28: 	    true then Cons(y, filtermap(f, ys))
//│ ║        	^^^^^^^^
//│ ╟── reference of type `true` is not an instance of type `number`
//│ ║  l.28: 	    true then Cons(y, filtermap(f, ys))
//│ ╙──      	    ^^^^
//│ ╔══[ERROR] type identifier not found: Tuple#2
//│ ╙──
//│ fun filtermap: ((error | Cons['A] | Nil) -> number & (Cons['A] | Nil) -> error, Cons['A0] | Nil,) -> (Cons['A1] | Nil | error)
//│   where
//│     'A := 'A0
//│     'A0 <: nothing
//│ Code generation encountered an error:
//│   unknown match case: Tuple#2

module True
module False
//│ module True()
//│ module False()

class Pair[A, B](lhs: A, rhs: B)
//│ class Pair[A, B](lhs: A, rhs: B)

fun filtermap(f, xs) = if xs is
  Nil then Nil
  Cons(y, ys) then if f(y) is
    True then filtermap(f, ys)
    False then Cons(y, filtermap(f, ys))
    Pair(True, z) then Cons(z, filtermap(f, ys))
//│ fun filtermap: ('head -> (False | Pair[anything, 'A] | True), Cons['head] | Nil,) -> (Cons['A] | Nil)
//│   where
//│     'head <: 'A
```

**Comment by chengluyu** [comment]
- [ ] Fix unhygienic bindings in [HygienicBindings.mls](https://github.com/chengluyu/mlscript/blob/ucs-paper/shared/src/test/diff/ucs/HygienicBindings.mls) and shared/src/test/diff/ucs/Hygiene.mls
- [ ] Should report warnings in shared/src/test/diff/ucs/Wildcard.mls
- [ ] Proper errors in shared/src/test/diff/ucs/PlainConditionals.mls
- [x] Some parser failures in shared/src/test/diff/ucs/ParseFailures.mls
- [ ] Support `or` in shared/src/test/diff/ucs/Or.mls
- [x] Leading `and` in shared/src/test/diff/ucs/LeadingAnd.mls
- [x] Incomplete example in shared/src/test/diff/ucs/JSON.mls

**Comment by chengluyu** [comment]
- [ ] Warning message regression. It should report the first duplicated branch.
https://github.com/chengluyu/mlscript/blob/ee1ab193234e9d59ad0ce3fa82e2c922efd8d56e/shared/src/test/diff/ucs/DirectLines.mls#L50-L63 
- [ ] Show terms properly, not using the internal debug string. https://github.com/chengluyu/mlscript/blob/ee1ab193234e9d59ad0ce3fa82e2c922efd8d56e/shared/src/test/diff/ucs/Exhaustiveness.mls#L51

**Comment by chengluyu** [comment]
- [x] Give warnings for non-conditional UCS. See https://github.com/hkust-taco/mlscript/blob/ee1ab193234e9d59ad0ce3fa82e2c922efd8d56e/shared/src/test/diff/nu/BadUCS.mls#L75
   
   **Update as of the introduction of new desugarer in Jan 2024**: This case is interesting, it means that we bind `x` to `y` which shadows parameter `y`, but someone may think it means if x == y then 0.
- [ ] Precise scrutinee tracking and merge explicit let bindings: https://github.com/hkust-taco/mlscript/blob/66d41f279648dd67507d442fa96330bec17075e7/shared/src/test/diff/ucs/HygienicBindings.mls#L31

**Comment by LPTK** [comment]
- [ ] One more hygienic bindings thing to make sure and address

    https://github.com/hkust-taco/mlscript/blob/687f39d8ebf4d649622e40ecba2af6ac09c3400f/shared/src/test/diff/ucs/CrossBranchCapture.mls#L8-L12

 - [ ] Warn against shadowing pattern variables

    https://github.com/hkust-taco/mlscript/blob/687f39d8ebf4d649622e40ecba2af6ac09c3400f/shared/src/test/diff/ucs/CrossBranchCapture.mls#L49-L52

**Comment by LPTK** [comment]
- [ ] It seems that this should work, but is currently warned about due to an overly restrictive implementation:
    ```fs
    fun fold(opt, k, d) = if opt is
      None then d
      refined(Some) then k(opt)
      else k(opt)
    //│ ╔══[WARNING] inconsistent refined pattern
    //│ ║  l.67:     None then d
    //│ ║            ^^^^
    //│ ╟── pattern `Some` is refined
    //│ ║  l.68:     refined(Some) then k(opt)
    //│ ║                    ^^^^
    //│ ╟── but pattern `None` is not refined
    //│ ║  l.67:     None then d
    //│ ╙──          ^^^^
    ```

**Comment by LPTK** [comment]
- [ ] Currently, `or` is not supported – see: https://github.com/hkust-taco/mlscript/blob/ac5ce9c33d90302a793e94032219d76e523fd502/hkmc2/shared/src/test/mlscript/ucs/general/LogicalConnectives.mls#L39-L43

**Comment by chengluyu** [comment]
### Refactorings

- Rewrite the `Desugarer`. Currently, `semantics.Pattern` is not used by `Desugarer`, which makes it unable to support many useful patterns.
- Some refactoring of `FlatPattern` and `Pattern` can be postponed until the `Desugarer` is rewritten.  
- A lot of the work for checking arguments and pattern arguments is done in `Normalization`. This should be handled in the `NaiveCompiler` instead.

### Missing Features in UPS

Besides that, there are still some unimplemented features:
- [ ] Support tuple patterns in pattern definitions.
- [ ] Support locally recursive patterns using `as`. (Needs clarification)
- [ ] Implement compilation of string patterns. Although there are many examples, some string patterns still don't work correctly. https://github.com/hkust-taco/mlscript/blob/513b1ea61f0ce1c27220fdcdb39e8697e1e9e606/hkmc2/shared/src/test/mlscript/rp/regex/Simplification.mls#L18-L28

**Comment by chengluyu** [comment]
- [ ] There should be a guardedness check for diverging patterns. 

    ```
    pattern P = P
    
    1 is P
    //│ ═══[RUNTIME ERROR] RangeError: Maximum call stack size exceeded
    ```

**Comment by chengluyu** [comment]
- [x] Investigate why the first branch is removed without notice. 

    ```
    module BaseLib0 with
      class Foo(val x)
    
    :sjs
    module DerivedLib1 with
      val BaseLib: module BaseLib0 = BaseLib0
      fun testFoo = case
        BaseLib.Foo then 1
        _ then 0
    //│ JS (unsanitized):
    //│ let DerivedLib11;
    //│ (class DerivedLib1 {
    //│   static {
    //│     DerivedLib11 = DerivedLib1;
    //│     this.BaseLib = BaseLib01;
    //│   }
    //│   static get testFoo() {
    //│     let lambda;
    //│     lambda = (undefined, function (caseScrut) {
    //│       return 0
    //│     });
    //│     return lambda;
    //│   }
    //│   static toString() { return runtime.render(this); }
    //│   static [definitionMetadata] = ["module", "DerivedLib1"]; 
    //│ });
    ```

    EDIT: Seems fixed; see https://github.com/hkust-taco/mlscript/blob/05fcfb92198aa59d26261e29c2c92cb05e9acb41/hkmc2/shared/src/test/mlscript/ucs/general/CrossModules.mls#L6-L16

**Comment by chengluyu** [comment]
### From #336:

- [ ] We should probably separate pattern parameters from extraction parameters, for example, `S[Bit](a, b)`. See https://github.com/hkust-taco/mlscript/pull/336#discussion_r2501592388.
- [ ] The `ident` function in pattern elaboration. See https://github.com/hkust-taco/mlscript/pull/336#discussion_r2400826194.
- [ ] Reproduce and fix the case discussed in https://github.com/hkust-taco/mlscript/pull/336#discussion_r2501793329.

**Comment by LPTK** [comment]
- [x] Duplicate default branches when they are trivial/small (rather than sharing them with a join point).

**Comment by chengluyu** [comment]
- [x] ‼️ Normalization should use inheritance information. See https://github.com/hkust-taco/mlscript/pull/336#discussion_r2502004775.

**Comment by LPTK** [comment]
- [ ] After https://github.com/hkust-taco/mlscript/pull/457 is merged, make pattern variables local to the branches, as opposed to the status quo, eg in:
    ```fs
    class C(val x)
    
    :sir
    case
      C(x) then x + 1
    //│ ———————————————| Lowered IR |———————————————————————————————————————————————————————————————————————
    //│ let lambda⁰;
    //│ define lambda⁰ as fun lambda¹(caseScrut) {
    //│   let x, arg$C$0$;
    //│   match caseScrut
    //│     C⁰ =>
    //│       set arg$C$0$ = caseScrut.x⁰;
    //│       set x = arg$C$0$;
    //│       return +⁰(x, 1)
    //│     else
    //│       throw new globalThis⁰.Error⁰("match error")
    //│   end
    //│ };
    //│ lambda¹
    //│ —————————————————| Output |—————————————————————————————————————————————————————————————————————————
    //│ = fun
    ```
